CREATE TABLE xunil.blog_post
    (
    id INT NOT NULL AUTO_INCREMENT,
    content TEXT NOT NULL,
    create_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT pk_blog_post_id PRIMARY KEY (id)
    )
    ENGINE = InnoDB;
